### ISSUE TITLE
Old GPU and whisperx mode

### ISSUE THREAD

**Issue by friki67** [JSchmie/ScrAIbe-WebUI#28]
I was trying to use whisperx in my old gpu (GTX 1070), and I'm getting an error saying that my device is not capable of doing float16 compute efficiently.

So I went over this: https://github.com/SYSTRAN/faster-whisper/issues/42

Then I edited /usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py, in row 137 changed default compute type (it was compute_type) to "int8". Then it is unable to detect audio in my file. Then I changed it to "float32", and then it worked ok.

Now I have fixed it, but maybe you can detect if the gpu is float16 capable and if not set the compute_type for faster_whisper to "float32".

**Comment by JSchmie** [comment]
Hi, I do not think this will be a topic for us in the future, since backwards compatibility with old hardware is a huge rabbit hole. 
Furthermore, it is manly a faster Whisper problem than a ScrAIbe problem. 
But you should be able to use our [Customize.md](https://github.com/JSchmie/ScrAIbe-WebUI/blob/main/docs/Customize.md) to handle this problem by just parse: 

```yaml
scraibe_params:
    compute_type: "float32"
```

If you try it, please let me know if it works. If it does not work, it is indeed something we need to fix in the future.

**Comment by neohunter** [comment]
I'll test it as was having the same problem yesterday.

**Comment by friki67** [comment]
> If you try it, please let me know if it works. If it does not work, it is indeed something we need to fix in the future.

Yes, it worked for me. Thank you.
