### ISSUE TITLE
WhisperX mode not working

### ISSUE THREAD

**Issue by friki67** [JSchmie/ScrAIbe-WebUI#47]
Async mode. Whisper mode is working ok. WhisperX mode is throwing this output:

```
config.json: 100% 2.39k/2.39k [00:00<00:00, 17.9MB/s]
vocabulary.json: 100% 1.07M/1.07M [00:00<00:00, 2.65MB/s]
preprocessor_config.json: 100% 340/340 [00:00<00:00, 3.27MB/s]
tokenizer.json: 100% 2.48M/2.48M [00:00<00:00, 4.24MB/s]
model.bin: 100% 3.09G/3.09G [00:36<00:00, 84.1MB/s]
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.2.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../root/.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.3.0. Bad things might happen unless you revert torch to 1.x.
```

Then I receive the email with "SCRAIBE - An error occured during processing"

I'm using the docker container with Incus, in Rocky linux 9.4, updated today.

**Comment by JSchmie** [comment]
Hi, we know about an issue where whisperX does not work when you specify the language in the interface, did you do that? If you do, so I would recommend you to just let it unselected. Otherwise, I would recommend you to wait for the latest version we hope to launch next week. There we are switching from WhisperX to faster-whisper, this also should resolve your problem.

**Comment by friki67** [comment]
Yes. it works without specify the language. Thank you.
